# DO NOT DELETE

../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximNoC.h ../src_new_gpu_2/NoximTile.h ../src_new_gpu_2/NoximRouter.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximMain.h ../src_new_gpu_2/NoximBuffer.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximStats.h ../src_new_gpu_2/NoximPower.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximGlobalRoutingTable.h ../src_new_gpu_2/fc_router.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximLocalRoutingTable.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximReservationTable.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximProcessingElement.h
../src_new_gpu_2/NoximNoC.o: ../src_new_gpu_2/NoximGlobalTrafficTable.h
../src_new_gpu_2/NoximRouter.o: ../src_new_gpu_2/NoximRouter.h ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximRouter.o: ../src_new_gpu_2/NoximBuffer.h ../src_new_gpu_2/NoximStats.h
../src_new_gpu_2/NoximRouter.o: ../src_new_gpu_2/NoximPower.h ../src_new_gpu_2/NoximGlobalRoutingTable.h
../src_new_gpu_2/NoximRouter.o: ../src_new_gpu_2/NoximLocalRoutingTable.h
../src_new_gpu_2/NoximRouter.o: ../src_new_gpu_2/NoximReservationTable.h
../src_new_gpu_2/benchmark.o: ../src_new_gpu_2/benchmark.h ../src_new_gpu_2/constants.h
../src_new_gpu_2/fc_router.o: ../src_new_gpu_2/fc_router.h
../src_new_gpu_2/NoximProcessingElement.o: ../src_new_gpu_2/NoximProcessingElement.h
../src_new_gpu_2/NoximProcessingElement.o: ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximProcessingElement.o: ../src_new_gpu_2/NoximGlobalTrafficTable.h
../src_new_gpu_2/NoximBuffer.o: ../src_new_gpu_2/NoximBuffer.h ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximStats.o: ../src_new_gpu_2/NoximStats.h ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximStats.o: ../src_new_gpu_2/NoximPower.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximGlobalStats.h ../src_new_gpu_2/NoximNoC.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximTile.h ../src_new_gpu_2/NoximRouter.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximMain.h ../src_new_gpu_2/NoximBuffer.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximStats.h ../src_new_gpu_2/NoximPower.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximGlobalRoutingTable.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximLocalRoutingTable.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximReservationTable.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximProcessingElement.h
../src_new_gpu_2/NoximGlobalStats.o: ../src_new_gpu_2/NoximGlobalTrafficTable.h
../src_new_gpu_2/NoximGlobalRoutingTable.o: ../src_new_gpu_2/NoximGlobalRoutingTable.h
../src_new_gpu_2/NoximGlobalRoutingTable.o: ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximLocalRoutingTable.o: ../src_new_gpu_2/NoximLocalRoutingTable.h
../src_new_gpu_2/NoximLocalRoutingTable.o: ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximLocalRoutingTable.o: ../src_new_gpu_2/NoximGlobalRoutingTable.h
../src_new_gpu_2/NoximGlobalTrafficTable.o: ../src_new_gpu_2/NoximGlobalTrafficTable.h
../src_new_gpu_2/NoximGlobalTrafficTable.o: ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximReservationTable.o: ../src_new_gpu_2/NoximReservationTable.h
../src_new_gpu_2/NoximReservationTable.o: ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximPower.o: ../src_new_gpu_2/NoximPower.h ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximCmdLineParser.o: ../src_new_gpu_2/NoximCmdLineParser.h ../src_new_gpu_2/NoximMain.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximMain.h ../src_new_gpu_2/NoximNoC.h ../src_new_gpu_2/NoximTile.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximRouter.h ../src_new_gpu_2/NoximBuffer.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximStats.h ../src_new_gpu_2/NoximPower.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximGlobalRoutingTable.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximLocalRoutingTable.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximReservationTable.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximProcessingElement.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximGlobalTrafficTable.h ../src_new_gpu_2/fc_router.h
../src_new_gpu_2/NoximMain.o: ../src_new_gpu_2/NoximGlobalStats.h ../src_new_gpu_2/NoximCmdLineParser.h
