# DO NOT DELETE

../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximNoC.h ../src_new_gpu_3/NoximTile.h ../src_new_gpu_3/NoximRouter.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximMain.h ../src_new_gpu_3/NoximBuffer.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximStats.h ../src_new_gpu_3/NoximPower.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximGlobalRoutingTable.h ../src_new_gpu_3/fc_router.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximLocalRoutingTable.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximReservationTable.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximProcessingElement.h
../src_new_gpu_3/NoximNoC.o: ../src_new_gpu_3/NoximGlobalTrafficTable.h
../src_new_gpu_3/NoximRouter.o: ../src_new_gpu_3/NoximRouter.h ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximRouter.o: ../src_new_gpu_3/NoximBuffer.h ../src_new_gpu_3/NoximStats.h
../src_new_gpu_3/NoximRouter.o: ../src_new_gpu_3/NoximPower.h ../src_new_gpu_3/NoximGlobalRoutingTable.h
../src_new_gpu_3/NoximRouter.o: ../src_new_gpu_3/NoximLocalRoutingTable.h
../src_new_gpu_3/NoximRouter.o: ../src_new_gpu_3/NoximReservationTable.h
../src_new_gpu_3/benchmark.o: ../src_new_gpu_3/benchmark.h ../src_new_gpu_3/constants.h
../src_new_gpu_3/fc_router.o: ../src_new_gpu_3/fc_router.h
../src_new_gpu_3/NoximProcessingElement.o: ../src_new_gpu_3/NoximProcessingElement.h
../src_new_gpu_3/NoximProcessingElement.o: ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximProcessingElement.o: ../src_new_gpu_3/NoximGlobalTrafficTable.h
../src_new_gpu_3/NoximBuffer.o: ../src_new_gpu_3/NoximBuffer.h ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximStats.o: ../src_new_gpu_3/NoximStats.h ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximStats.o: ../src_new_gpu_3/NoximPower.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximGlobalStats.h ../src_new_gpu_3/NoximNoC.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximTile.h ../src_new_gpu_3/NoximRouter.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximMain.h ../src_new_gpu_3/NoximBuffer.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximStats.h ../src_new_gpu_3/NoximPower.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximGlobalRoutingTable.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximLocalRoutingTable.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximReservationTable.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximProcessingElement.h
../src_new_gpu_3/NoximGlobalStats.o: ../src_new_gpu_3/NoximGlobalTrafficTable.h
../src_new_gpu_3/NoximGlobalRoutingTable.o: ../src_new_gpu_3/NoximGlobalRoutingTable.h
../src_new_gpu_3/NoximGlobalRoutingTable.o: ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximLocalRoutingTable.o: ../src_new_gpu_3/NoximLocalRoutingTable.h
../src_new_gpu_3/NoximLocalRoutingTable.o: ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximLocalRoutingTable.o: ../src_new_gpu_3/NoximGlobalRoutingTable.h
../src_new_gpu_3/NoximGlobalTrafficTable.o: ../src_new_gpu_3/NoximGlobalTrafficTable.h
../src_new_gpu_3/NoximGlobalTrafficTable.o: ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximReservationTable.o: ../src_new_gpu_3/NoximReservationTable.h
../src_new_gpu_3/NoximReservationTable.o: ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximPower.o: ../src_new_gpu_3/NoximPower.h ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximCmdLineParser.o: ../src_new_gpu_3/NoximCmdLineParser.h ../src_new_gpu_3/NoximMain.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximMain.h ../src_new_gpu_3/NoximNoC.h ../src_new_gpu_3/NoximTile.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximRouter.h ../src_new_gpu_3/NoximBuffer.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximStats.h ../src_new_gpu_3/NoximPower.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximGlobalRoutingTable.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximLocalRoutingTable.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximReservationTable.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximProcessingElement.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximGlobalTrafficTable.h ../src_new_gpu_3/fc_router.h
../src_new_gpu_3/NoximMain.o: ../src_new_gpu_3/NoximGlobalStats.h ../src_new_gpu_3/NoximCmdLineParser.h
